import turtle

tina = turtle.Turtle()
tina.speed(10)
tina.hideturtle()
background = turtle.Screen()

# tina_background = raw_input("What color should the background be?")
# tina_color = raw_input("What color should Tina use to draw?")

# background.bgcolor(tina_background)
# tina.color(tina_color)

tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)
tina.left(45)
tina.forward(20)
tina.circle(40)

#Extra
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)
tina.left(46)
tina.forward(20)
tina.circle(40)


